name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: recursive

      - name: Setup node
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
        with:
          node-version-file: "./ui/.nvmrc"

      - name: Setup go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5
        with:
          go-version-file: "./go.mod"
          cache: false

      - name: Install dependencies
        run: npm install
        working-directory: ./ui

      - name: Build WASM
        run: ./build-wasm.sh && ./build-zxing.sh
        working-directory: .

      - name: Build Licenses
        run: ./build-licenses.sh
        working-directory: .

      - name: Build
        run: npm run build
        working-directory: ./ui

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: paper-backup
          path: ui/dist/index.html

